FROM node:18 AS deps
WORKDIR /app

COPY ./server/package*.json ./
RUN  npm install

FROM node:18 AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./server/ .
COPY --from=deps /app/package*.json ./
EXPOSE 3001
CMD ["npm", "start"]