FROM node:18 AS deps
WORKDIR /app

COPY ./client/package*.json ./
RUN  npm install

FROM node:18 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./client/ .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM node:18 AS runner
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=builder /app/ .
EXPOSE 3000
CMD ["npm", "start"]